### PR TITLE
LPS-119475 SF

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
ci.test:sf

**Comment by manoelcyreno** [comment]
ci:test:tango

**Comment by manoelcyreno** [comment]
ci:test:tango-analytics-cloud

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:tango

**Comment by manoelcyreno** [comment]
ci:test:tango-analytics-cloud

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:close

**Pull request closed without merging**
