### PR TITLE
LPS-96183 Export referenced experiences for draft fragments

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by manoelcyreno** [comment]
For me it ok, you can open the PR to BChan

**Pull request closed without merging**
