### PR TITLE
Master-qa-106109

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-106109

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82401.

**Pull request closed without merging**
