### PR TITLE
LPS 113979 Missing '('

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
The job ci:test:tango-analytics-cloud won't pass till the PR https://github.com/brianchandotcom/liferay-portal/pull/88934 is merged.

**Comment by manoelcyreno** [comment]
ci:forward

**Pull request closed without merging**
