### PR TITLE
master-qa-105714

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-105714

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81961.

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81962.

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/manoelcyreno/liferay-portal/pull/48.

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82045.

**Pull request closed without merging**
