### PR TITLE
LPS-103102 | Segmentation is not working after remove the user section

### PR DESCRIPTION
**Pull request by andresfulla**

### CODE REVIEW

**Comment by andresfulla** [comment]
ci:test:sf

**Comment by andresfulla** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by andresfulla** [comment]
Just started reviewing 💃 <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
