### PR TITLE
LPS-106385, LPS-106387 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-106385
https://issues.liferay.com/browse/LPS-106387

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test

**Comment by manoelcyreno** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82802.

**Pull request closed without merging**
