### PR TITLE
LPS-140130 Organize the LOL test suite and Create some stubs

### PR DESCRIPTION
**Pull request by manoelcyreno**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:relevant

**Comment by manoelcyreno** [comment]
ci:test:liferay-online

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:liferay-online

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:liferay-online

**Comment by manoelcyreno** [comment]
ci:reevaluate:1107401_5008

**Comment by manoelcyreno** [comment]
ci:test:liferay-online

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:reevaluate:1257401_479

**Comment by manoelcyreno** [comment]
ci:reevaluate:1307401_714

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:reevaluate:1257401_479

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by nkkwon** [comment]
Taking a look right now!

**Comment by nkkwon** [comment]
@manoelcyreno 
Analysis Details:

It looks like the tests are failing from the POSHI validation with `     [exec] Invalid property value 'lfr Online' for property name 'testray.main.component.name'` That you added in LiferayOnlineCoverBugs.testcase from this commit https://github.com/manoelcyreno/liferay-portal/pull/157/commits/c2944fc5b01e5945059ae5156e2988df94cf4c7c

**Comment by manoelcyreno** [comment]
tnks @nkkwon , lets see if its enough... :D

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:liferay-online

**Comment by manoelcyreno** [comment]
moving https://github.com/manoelcyreno/liferay-portal/pull/158

**Pull request closed without merging**
