### PR TITLE
LPS-110076 To add content pages to smoke test

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-110076

Tested in david-gutierrez-mesa#12

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:stable

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86467.

**Pull request closed without merging**
