### PR TITLE
LPS-104330 Add testcase to assert the page template tabs are in correct application

### PR DESCRIPTION
**Pull request by brookedalton**

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:relevant:nocompile

**Comment by brookedalton** [comment]
ci:reopen

**Comment by brookedalton** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80812.

**Pull request closed without merging**
