### PR TITLE
LPS-121209 Fix ExperienceCreateExperience#DisplayUserExperience and ExperienceCreateExperience#EditInlineTextExperience

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by manoelcyreno** [comment]
@CarlosBrichete  fix the failures and send it again.

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:tango

**Comment by manoelcyreno** [comment]
ci:test:tango

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
