### PR TITLE
Master-qa-106274

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-106274

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82486. [See changes here.](https://github.com/manoelcyreno/liferay-portal/compare/81212c0d3c4b~1...81212c0d3c4b)

**Pull request closed without merging**
