### PR TITLE
LPS-118966 Smoke Poshi Automation: Edit experience audience and name and delete experience

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Hey @manoelcyreno, can you review this Poshi test? 😄  I completed it with the creation of a new segment when editing the experience.

cc: @carlosbrichete @Tim-Cao

**Comment by manoelcyreno** [comment]
ci:test:tango

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:forward

**Pull request closed without merging**
