### PR TITLE
LPS-99762 Test order by relevance in journal article search

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
everything sounds good to me.

**Comment by pavel-savinov** [comment]
@manoelcyreno, could you please forward it to Brian then?

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78115.

**Pull request closed without merging**
