### PR TITLE
LPS-110662 Reduce what is tested in Smoke or Content Pages

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-110662

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
ci:test:stable

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
please,
send this PR to yourself and when 
ci:test:sf + ci:test:stable + ci:test:relevant are passing...
use the ci:forward

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86671.

**Pull request closed without merging**
