### PR TITLE
LPS-120617 SF

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Pull request submitted to https://github.com/manoelcyreno/liferay-portal/pull/148. [See changes here.](https://github.com/manoelcyreno/liferay-portal/compare/9ce2288632b9~1...9ce2288632b9)

**Pull request closed without merging**
