### PR TITLE
 LPS-99112 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-99112

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
@liulukiwi these failures have something related to your code / your changes?
If not... You can send this PR to Brian...

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @manoelcyreno , LocalFile.Breadcrumb#DisableShowPage  is related to LRQA-49480, the other two looks fluke, run the ci relevant again to check.

**Comment by liulukiwi** [comment]
No unique failures.
Pushed to BChan.
master: brianchandotcom/liferay-portal#777087.2.x
7.2.x: brianchandotcom/liferay-portal-ee#26284

**Pull request closed without merging**
