### PR TITLE
LPS-96828 Don't persist default preferences in case when they don't exist

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :)

**Comment by manoelcyreno** [comment]
Hi @pavel-savinov ,
The manual tests for the issue [LPS-96828](https://issues.liferay.com/browse/LPS-96828) had passed in a manual validation, but the _ci:test:relevant_ present two failures, can you take a look on this, please?

**Comment by epgarcia** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by epgarcia** [comment]
@manoelcyreno Can you please close this PR? I rebased it and run the test on https://github.com/epgarcia/liferay-portal/pull/896. Thanks

**Pull request closed without merging**
