### PR TITLE
LRQA-58936

### PR DESCRIPTION
**Pull request by Adriverforlife**
Post Upgrade Checks for 7.1 to 7.3

### CODE REVIEW

**Comment by Adriverforlife** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
@Adriverforlife , can you take a look on it?

**Comment by Adriverforlife** [comment]
ci:forward

**Comment by Adriverforlife** [comment]
@manoelcyreno weird, it passed when I checked it against my master. I re-rebased and SFed again this morning. Should be good now.

**Pull request closed without merging**
