### PR TITLE
Master-qa-107260

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-107260

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Hi @Tim-Cao ,

Can you check your XML files according to this BChan comments: https://github.com/brianchandotcom/liferay-portal/pull/83563#issuecomment-576773851

Can you change your JSON files to not stay in one line according to this BChan comments: https://github.com/brianchandotcom/liferay-portal/pull/82672#issuecomment-570303592

**Comment by Tim-Cao** [comment]
Hi @manoelcyreno,
I will modify the format of JSON files, Could you give me an example about format of XML file? The above format is fit to HTML file.

**Comment by manoelcyreno** [comment]
Hi @Tim-Cao , You can use this kind of example to format the XML, I know that this is an HTML, but the idea is the same...
`<tag>
<tab_key_to_create_the_space><tag>
<tab_key_to_create_the_space><tab_key_to_create_the_space><tag>something</tag>
<tab_key_to_create_the_space></tag>
</tag>`

**Pull request closed without merging**
