### PR TITLE
LPS-94964 JS error when clicking copy button on cookies field in segments editor

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by manoelcyreno** [comment]
For me, it ok, you can open the PR to BChan

**Pull request closed without merging**
