### PR TITLE
LPS-101230 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-101230

### CODE REVIEW

**Comment by manoelcyreno** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
The failures are not related to my pull, analysis them here:
https://testray.liferay.com/zh/home/-/testray/case_results/index?testrayBuildId=793635975

**Comment by manoelcyreno** [comment]
cool! you can send to bchan, tnks.

**Comment by liulukiwi** [comment]
Pushed to BChan.
 brianchandotcom/liferay-portal#78878

**Pull request closed without merging**
